version: "3"
services:
  db:
    image: postgres:latest
    container_name: nawy-db
    environment:
      - POSTGRES_USER=nawy
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=nawy
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nawy-backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: nawy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  database:
