WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
COPY ./env.example ./env

# Disable telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# Build the app
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]