FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Disable telemetry
ENV NEXT_TELEMETRY_DISABLED 1

ENV NEXT_PUBLIC_API_URL=http://backend:5000/v1

# Build the app
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]